<?php

namespace Database\Seeders;

use App\Genre;

class GenresSeeder extends BaseSeeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        foreach ($this->genres() as $genre) {
            Genre::create([
                'name' => $genre,
            ]);
        }
    }

    private function genres()
    {
        return [
            'Acapella',
            'Acid',
            'Acid Jazz',
            'Acid Punk',
            'Acoustic',
            'Alternative',
            'Alternative Rock',
            'Ambient',
            'Anime',
            'Avantgarde',
            'Ballad',
            'Bass',
            'Beat',
            'Bebob',
            'Big Band',
            'Black Metal',
            'Bluegrass',
            'Blues',
            'Booty Bass',
            'BritPop',
            'Cabaret',
            'Celtic',
            'Chamber Music',
            'Chanson',
            'Chorus',
            'Christian Gangsta',
            'Christian Rap',
            'Christian Rock',
            'Classic Rock',
            'Classical',
            'Club',
            'Club-House',
            'Comedy',
            'Contemporary C',
            'Country',
            'Crossover',
            'Cult',
            'Dance',
            'Dance Hall',
            'Darkwave',
            'Death Metal',
            'Disco',
            'Dream',
            'Drum & Bass',
            'Drum Solo',
            'Duet',
            'Easy Listening',
            'Electronic',
            'Ethnic',
            'Euro-House',
            'Euro-Techno',
            'Eurodance',
            'Fast Fusion',
            'Folk',
            'Folk-Rock',
            'Folklore',
            'Freestyle',
            'Funk',
            'Fusion',
            'Game',
            'Gangsta',
            'Goa',
            'Gospel',
            'Gothic',
            'Gothic Rock',
            'Grunge',
            'Hard Rock',
            'Hardcore',
            'Heavy Metal',
            'Hip-Hop',
            'House',
            'Humour',
            'Indie',
            'Industrial',
            'Instrumental',
            'Instrumental Pop',
            'Instrumental Rock',
            'JPop',
            'Jazz',
            'Jazz+Funk',
            'Jungle',
            'Latin',
            'Lo-Fi',
            'Meditative',
            'Merengue',
            'Metal',
            'Musical',
            'National Folk',
            'Native US',
            'Negerpunk',
            'New Age',
            'New Wave',
            'Noise',
            'Oldies',
            'Opera',
            'Other',
            'Polka',
            'Polsk Punk',
            'Pop',
            'Pop-Folk',
            'Pop/Funk',
            'Porn Groove',
            'Power Ballad',
            'Pranks',
            'Progressive Rock',
            'Psychadelic',
            'Psychedelic Rock',
            'Punk',
            'Punk Rock',
            'R&B',
            'Rap',
            'Rave',
            'Reggae',
            'Retro',
            'Revival',
            'Rhytmic Soul',
            'Rock',
            'Rock & Roll',
            'Salsa',
            'Samba',
            'Satire',
            'Showtunes',
            'Ska',
            'Slow Jam',
            'Slow Rock',
            'Sonata',
            'Soul',
            'Sound Clip',
            'Soundtrack',
            'Southern Rock',
            'Space',
            'Speech',
            'Swing',
            'Symphonic Rock',
            'Symphony',
            'SynthPop',
            'Tango',
            'Techno',
            'Techno-Industrial',
            'Terror',
            'Thrash Metal',
            'Top 40',
            'Trailer',
            'Trance',
            'Tribal',
            'Trip-Hop',
            'Vocal',
            'Primus',
            'Racecar Sampler',
            'Turbo Folk Micro-Orchestra',
            'Electric Violin',
            'Electronica',
            'Chillout',
            'Electroacoustic',
            'Ambigusic',
            'World Fusion',
            'New Music',
            'Dark Ambient',
            'Garage',
            'World',
            'DJ Tools',
            'Dubstep',
            'Glitch Hop',
            'Electro',
            'Liquid Drum & Bass',
            'Liquid Dubstep',
            'Chillstep',
            'Drumstep',
            'Dram Rock',
        ];
    }
}
